runtime: nodejs22
env: standard
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 5
handlers:
  - url: /.*
    script: auto
beta_settings:
  cloud_sql_instances: clone-twitter-503801:asia-northeast3:clone-twitter-db
env_variables:
  NODE_ENV: production
  PORT: "8080"
  INSTANCE_CONNECTION_NAME: clone-twitter-503801:asia-northeast3:clone-twitter-db
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_DATABASE: ${DB_DATABASE}
